### PR TITLE
added package.json

### PR DESCRIPTION
**Pull request by Tatsujinichi**
new versions of cordova require plugins to have a package.json

### CODE REVIEW

**Comment by tbrebant** [comment]
I don't know if we should do our changes on a different branch. That's what we did for example with the [cordova-plugin-media](https://github.com/Wizcorp/cordova-plugin-media/tree/wild) and the ***wild*** branch, because our changes were not merged in the main repo and we were not receiving any answer.

Here the original repo doesn't seems to be updated anymore so it may be not that important, but I wonder what's the best practice.

Outside of this, no problem with the content from my point of view.

**Comment by Tatsujinichi** [comment]
@jrouault what do you think Jerome?  Should I create a new branch?

**Comment by ronkorving** [comment]
I'll give my 2 cents as well. The upstream repo has been untouched for 3 years. I think we can reasonably call our own fork "the main repo" at this point, and shouldn't care about what's going on upstream (since... there's nothing going on).

**Comment by jrouault** [comment]
I agree with @ronkorving. This can go on `master` IMO.

**Review by jrouault — APPROVED** [review]

**Review by tbrebant — APPROVED** [review]

**Pull request merged**
